name: Maven CI

on:
  push:
    branches:
      - '**'
  pull_request:

permissions:
  contents: read

jobs:
  verify:
    uses: UltiKits/ci-workflows/.github/workflows/maven-ci.yml@v1
    with:
      needs-nms: false
